"""Per-turn loss masking utilities for multi-turn (agentic) RL.

In agentic RL, trajectories contain alternating model turns and environment
turns. We only want policy gradients on model-generated tokens, not on
environment-injected tokens (tool results, user messages, etc.).

The core training pipeline already handles this correctly:
``trajectory_to_data`` in ``data_processing.py`` assigns ``mask=1.0`` to
action tokens and ``mask=0.0`` to observation tokens. This module provides
additional utilities for *inspecting* and *validating* per-turn masks,
which is useful when debugging new environments.

Token-level mask layout for a 3-turn trajectory::

    [system + user prompt] [model turn 1] [tool result 1] [model turn 2] [tool result 2] [model turn 3]
    |---- mask = 0.0 ----| |-- mask 1.0 -| |-- mask 0.0 -| |-- mask 1.0 -| |-- mask 0.0 -| |-- mask 1.0 -|
    |---- observation 1 --| |-- action 1 -| |-- delta ob -| |-- action 2 -| |-- delta ob -| |-- action 3 -|

This holds because ``EnvFromMessageEnv`` re-renders the full conversation at
each turn. The new observation is the old observation + previous action +
environment response, so ``trajectory_to_data`` sees it as a prefix extension
and correctly identifies the "delta" (environment response tokens) as mask=0.
"""

from __future__ import annotations

from dataclasses import dataclass

from tinker_cookbook.rl.data_processing import (
    FlatOb,
    _flat_ob_token_len,
    _flatten_chunks,
    _is_prefix,
)
from tinker_cookbook.rl.types import Trajectory


@dataclass(frozen=True)
class TurnMaskInfo:
    """Diagnostic information about token-level masking for one turn.

    Attributes:
        turn_index: 0-based turn number.
        observation_tokens: Number of new observation tokens in this turn
            (the "delta" -- tokens added by the environment since last turn).
        action_tokens: Number of tokens generated by the model.
        observation_mask: Mask value for observation tokens (always 0.0).
        action_mask: Mask value for action tokens (always 1.0).
    """

    turn_index: int
    observation_tokens: int
    action_tokens: int
    observation_mask: float = 0.0
    action_mask: float = 1.0


@dataclass(frozen=True)
class TrajectoryMaskSummary:
    """Summary of token-level masking for an entire trajectory.

    Attributes:
        turns: Per-turn mask information.
        total_tokens: Total tokens in the trajectory.
        masked_tokens: Tokens with mask=0 (observation/environment tokens).
        unmasked_tokens: Tokens with mask=1 (model-generated action tokens).
        n_datums: Number of training datums this trajectory will produce.
            Usually 1 for multi-turn conversations (because observations
            share a common prefix), but can be >1 if the environment resets
            the conversation mid-episode.
    """

    turns: list[TurnMaskInfo]
    total_tokens: int
    masked_tokens: int
    unmasked_tokens: int
    n_datums: int


def compute_trajectory_mask_summary(trajectory: Trajectory) -> TrajectoryMaskSummary:
    """Compute a diagnostic summary of how loss masking will be applied.

    This mirrors the logic in ``trajectory_to_data`` but only computes
    mask metadata without constructing actual training datums. Useful for
    logging, debugging, and validating that environment tokens are correctly
    masked.

    Args:
        trajectory: A completed trajectory from a rollout.

    Returns:
        A TrajectoryMaskSummary describing per-turn and aggregate mask stats.

    Example::

        summary = compute_trajectory_mask_summary(trajectory)
        for turn in summary.turns:
            print(f"Turn {turn.turn_index}: "
                  f"{turn.observation_tokens} obs tokens (masked), "
                  f"{turn.action_tokens} action tokens (unmasked)")
        print(f"Total: {summary.unmasked_tokens}/{summary.total_tokens} tokens receive gradient")
    """
    turns: list[TurnMaskInfo] = []
    accumulated: FlatOb = []
    n_datums = 0
    total_obs = 0
    total_act = 0

    for i, transition in enumerate(trajectory.transitions):
        ob_flat = _flatten_chunks(transition.ob.chunks)
        ac_len = len(transition.ac.tokens)

        if len(accumulated) == 0:
            delta_len = _flat_ob_token_len(ob_flat)
            n_datums += 1
        elif _is_prefix(accumulated, ob_flat):
            delta_flat = ob_flat[len(accumulated):]
            delta_len = _flat_ob_token_len(delta_flat)
        else:
            # Sequence break -- new datum will be created
            delta_len = _flat_ob_token_len(ob_flat)
            accumulated = []
            n_datums += 1

        turns.append(TurnMaskInfo(
            turn_index=i,
            observation_tokens=delta_len,
            action_tokens=ac_len,
        ))

        total_obs += delta_len
        total_act += ac_len

        # Mirror accumulation logic from trajectory_to_data
        accumulated = list(ob_flat) + list(transition.ac.tokens)

    return TrajectoryMaskSummary(
        turns=turns,
        total_tokens=total_obs + total_act,
        masked_tokens=total_obs,
        unmasked_tokens=total_act,
        n_datums=n_datums,
    )
